#!/usr/bin/env ruby

require 'rake'
require 'rails/generators'
require 'allages'

spec = Gem::Specification.find_by_name 'allages'
rakefile = "#{spec.gem_dir}/lib/allages/Rakefile"
load rakefile

task = ARGV[0]

if File.file? ".allages.yml"
  yaml = YAML.load_file ".allages.yml"
  if yaml
    Allages.configure do |config|
      yaml.each do |setting, value|
        config.send(setting + "=", value)
      end
    end
  end
end

unless task
  puts "No task was given"
else
  Rake::Task["allages:#{task}"].execute
end