#!/usr/bin/env ruby

require 'rake'
require 'rails/generators'
require 'allages'

spec = Gem::Specification.find_by_name 'allages'
rakefile = "#{spec.gem_dir}/lib/allages/Rakefile"
load rakefile

task = ARGV[0]

unless task
  puts "No task was given"
else
  Rake::Task["allages:#{task}"].execute
end